### ISSUE TITLE
class-transformer peer dependency doesn't get installed with yarn

### ISSUE THREAD

**Issue by backmeupplz** [iyobo/amala#29]
I have no idea why. `yarn.lock` didn't even register `class-transformer`. After adding it with `yarn add class-transformer` explicitly, everything works.

**Comment by iyobo** [comment]
Apologies. All peer dependencies have been turned into "*" version dependencies so that it either gets the most recent version, or uses whatever version you are already using.

PLEASE NOTE: This project initially existed as `koa-ts-controllers`. It is now named `amala`.
No further updates will be made under `koa-ts-controllers`.
Please replace `koa-ts-controllers` with `amala` in your code base.
i.e
```
yarn remove koa-ts-controllers
yarn add amala
```

In this new re-imagening of the project, You need no other dependency but `amala` to get running creating your REST applications. The project will persist and be maintained under this new name `amala` on github and npm.

Apologies again for the inconvenience.

**Comment by backmeupplz** [comment]
@iyobo thank you a lot for the clarification!
